version: "3.8"
services:
#  backend:
#    build: ./backend
#    container_name: fastapi
#    ports:
#      - "80:80"
  daily_predictor:
    build: ./stock_predictor
    container_name: daily_predictor
    volumes:
    - ./stock_predictor/:/app
    environment:
      API_KEY: "96a77462a7a68eebbc94ffbd0e7324e48c197257465a4f5a9d5ca40dc4fb0112"
      TRAIN_TYPE: "histoday"
      MONGO_URL: db
      MONGO_PORT: 27017
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "stocks"
    ports:
      - 27017:27017
    volumes:
    - db_data:/data/db

volumes:
  db_data: {}